# NumPyによる数値計算1

In [1]:
import numpy as np

## 練習問題1

$
  A = \left[
      \begin{array}{cc}
      1 & -2 \\
      4 & 3 \\
      \end{array}
      \right]
$
のとき、3$A$+5$I$を計算せよ。

In [4]:
A = np.array([[1, -2], [4, 3]])
I = np.eye(2)

ans1 = 3 * A + 5 * I
print(ans1)

[[ 8. -6.]
 [12. 14.]]


## 練習問題2

In [6]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

## 練習問題3

In [8]:
arr2d[2]

array([7, 8, 9])

## 練習問題4

In [10]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1] += arr2d[0]*2
arr2d

array([[ 1,  2,  3],
       [ 6,  9, 12],
       [ 7,  8,  9]])

## 練習問題5

0から99までのndarrayを生成し、3の倍数だけ取り出してみよう。

In [11]:
arr1d = np.arange(100)
arr1d[arr1d%3==0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

## 練習問題6

arr = np.arange(32).reshape((8, 4))

に対し、

array([23, 17, 11, 18])

をファンシーインデックス参照で取り出せ。

In [12]:
arr = np.arange(32).reshape((8, 4))
arr[[5, 4, 2, 4], [3, 1, 3, 2]]

array([23, 17, 11, 18])

## 練習問題7

In [20]:
arr = np.arange(16).reshape((2, 2, 4))
arr.transpose(1, 0, 2).swapaxes(1, 2)

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])